import React, {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/apiClient';
import {prepareRingback} from '@/lib/telephony/ringback';
import {clearActivePhoneConnection,createBrowserClient,setActivePhoneConnection,setOperatorMode,hasActivePhoneCall} from '@/lib/telephony/browserClient';
import {Button} from '@/components/ui/button';
const MODES=[['available','Available'],['standby','Standby'],['do_not_disturb','Do not disturb'],['break','Break'],['after_call_work','After-call work']];
export default function AgentPhoneConnection({user}) {
 const client=useRef(null),audio=useRef(null),generation=useRef(0),modeRef=useRef('offline');
 const [status,setStatus]=useState('offline'),[mode,setMode]=useState('offline'),[incoming,setIncoming]=useState(null),[error,setError]=useState(null);
 const sessionKey=`gms-phone-session:${user?.id}:${user?.organization_id}`;
 const restoredMode=useRef('available');
 const presence=async value=>{modeRef.current=value;setMode(value);setOperatorMode(value);if(value!=='offline' && value!=='busy')sessionStorage.setItem(sessionKey,value);await api.telephonyAction(user,'set_availability',{status:value});};
 useEffect(()=>{const timer=setInterval(()=>{if(client.current)api.telephonyAction(user,'set_availability',{status:modeRef.current}).catch(()=>{});},30000);return()=>{clearInterval(timer);generation.current++;clearActivePhoneConnection(client.current);client.current?.disconnect();client.current=null;setOperatorMode('offline');};},[user?.id,user?.organization_id]);
 const connect=async()=>{const current=++generation.current;setError(null);setStatus('connecting');try {
  const permission=await navigator.mediaDevices.getUserMedia({audio:true});permission.getTracks().forEach(track=>track.stop());prepareRingback();
  const session=await api.telephonyAction(user,'browser_session');
  const connection=await createBrowserClient(session,{audio:audio.current,onIncoming:setIncoming,onState:value=>{setStatus(value);if(value==='active')presence('busy').catch(()=>{});else if(value==='available' && modeRef.current==='busy')presence('after_call_work').catch(()=>{});},onError:error=>{setError(error?.message || 'Phone connection lost. Re-enable outbound calls.');}});
  if(current!==generation.current){connection.disconnect();return;}client.current=connection;await connection.connect();setActivePhoneConnection(connection);await presence(restoredMode.current);
 }catch(error){client.current?.disconnect();clearActivePhoneConnection();client.current=null;setStatus('offline');setOperatorMode('offline');setError(error.message);}};
 useEffect(()=>{let live=true;const saved=sessionStorage.getItem(sessionKey);if(saved){restoredMode.current=MODES.some(([value])=>value===saved)?saved:'available';navigator.permissions?.query({name:'microphone'}).then(permission=>{if(live && permission.state==='granted' && !client.current)connect();}).catch(()=>{});}return()=>{live=false;};},[sessionKey]);
 const disconnect=async()=>{if(hasActivePhoneCall()){setError('End the active call before going offline.');return;}sessionStorage.removeItem(sessionKey);generation.current++;clearActivePhoneConnection(client.current);client.current?.disconnect();client.current=null;setIncoming(null);setStatus('offline');await presence('offline');};
 const answer=async()=>{try{await incoming.accept();setIncoming(null);setStatus('active');await presence('busy');await audio.current?.play();}catch(error){setError(error.message);}};
 return <section className="rounded-lg border bg-card p-4 space-y-3" aria-label="Agent phone control panel"><audio ref={audio} autoPlay/><div className="grid gap-4 md:grid-cols-[1fr_auto_auto_auto] items-center"><strong className="text-lg">Agent phone control</strong><span className="rounded-full bg-muted px-3 py-2 text-sm capitalize">Phone: {status}</span><span className="rounded-full bg-muted px-3 py-2 text-sm capitalize">Status: {mode.replace(/_/g,' ')}</span><div className="flex flex-wrap gap-3 justify-end"><Button disabled={status==='connecting'} onClick={()=>{(client.current?disconnect():connect()).catch(error=>setError(error.message));}}>{client.current?'Go offline':status==='connecting'?'Enabling…':'Enable outbound calls'}</Button>{client.current && <select aria-label="Agent work status" value={mode==='busy'?'busy':mode} disabled={hasActivePhoneCall()} onChange={event=>presence(event.target.value).catch(error=>setError(error.message))}>{mode==='busy' && <option value="busy">On call</option>}{MODES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>}</div></div><p className="text-xs text-muted-foreground">After a refresh, your phone reconnects automatically when microphone permission is already granted. Otherwise, enable it once. Open a lead and click Call to dial. Standby, Do not disturb and Break pause outbound calling.</p>{incoming && <div role="alert"><strong>Incoming call</strong><Button onClick={answer}>Answer incoming call</Button><Button variant="outline" onClick={()=>{incoming.reject();setIncoming(null);}}>Decline</Button></div>}{error && <p role="alert" className="text-destructive">{error}</p>}</section>;
}
